title: Afique Sadique
#logo: folder/file.jpg
description:  Database Management, Discovering pattern from data (Data Mining), Machine Learning, Encryption/Decryption, Unix/Linux Operating System, Interaction between humans and computers (HCI) are some of the fields that I have knowledge upon and am eager to enhance them.
show_downloads: false
theme: jekyll-theme-minimal
