title: Afique Sadique
#logo: folder/file.jpg
description:  Discovering knowledge from data (patterns of data), Machine Learning, encryption/decryption, Unix/Linux, Operating System, Interaction between humans and computers are some of the fields that I have knowledge upon  and eager to enhance.
show_downloads: false
theme: jekyll-theme-minimal
