title: Afique Sadique
logo: /assets/img/pp.png
description: Completed Bachelor of Science in Computer Science & Engineering, while majoring in Information System.
show_downloads: false
theme: jekyll-theme-minimal
